CREATE DATABASE Academy
GO
USE Academy
GO

CREATE TABLE Groups(
ID INT PRIMARY KEY IDENTITY(1,1),
[Name] NVARCHAR(10) NOT NULL CHECK([Name]!=' ') UNIQUE,
RATING INT NOT NULL CHECK(Rating BETWEEN 1 AND 5),
[Year] INT NOT NULL CHECK([Year]>1 AND [Year]<5)

)

CREATE TABLE Chairs(
Id INT PRIMARY KEY IDENTITY(1,1),
Financing INT NOT NULL CHECK(Financing>=0) DEFAULT 0,
[Name] NVARCHAR(100) NOT NULL CHECK([Name]!=' ') UNIQUE,

)

CREATE TABLE Faculties(
ID INT PRIMARY KEY IDENTITY(1,1),
[Name] NVARCHAR(100) NOT NULL CHECK([Name]!=' ') UNIQUE,
)

CREATE TABLE Teachers(
ID INT PRIMARY KEY IDENTITY(1,1),
EmployementDate DATE NOT NULL CHECK(EmployementDate>='01.01.1990'),
[Name] NVARCHAR(MAX) NOT NULL CHECK([Name]!=' '),
Premium INT NOT NULL CHECK(0<=Premium) DEFAULT 0,
Salary INT NOT NULL CHECK(0<Salary),
Surname NVARCHAR(MAX) NOT NULL CHECK([Surname]!=' ')

)

